import OpenWangZaiConfig from './src/model/model';


let intents = '{"intents":[{"intent":"AnswerIntent","slots":[{"name":"Answer","type":"LIST_OF_ANSWERS"}]},{"intent":"AnswerOnlyIntent","slots":[{"name":"Answer","type":"LIST_OF_ANSWERS"}]},{"intent":"AMAZON.StartOverIntent"},{"intent":"DontKnowIntent"},{"intent":"AMAZON.RepeatIntent"},{"intent":"AMAZON.HelpIntent"},{"intent":"AMAZON.YesIntent"},{"intent":"AMAZON.NoIntent"},{"intent":"AMAZON.StopIntent"},{"intent":"AMAZON.CancelIntent"},{"intent":"AMAZON.PauseIntent"},{"intent":"AMAZON.ResumeIntent"}]}';
let customTypes = '{"LIST_OF_ANSWERS":["Actinium","Aluminum","Americium","Antimony","Argon","Arsenic","Astatine","Barium","Berkelium","Beryllium","Bismuth","Bohrium","Boron","Bromine","Cadmium","Calcium","Californium","Carbon","Cerium","Cesium","Chlorine","Chromium","Cobalt","Copper","Curium","Darmstadtium","Dubnium","Dysprosium","Einsteinium","Erbium","Europium","Fermium","Fluorine","Francium","Gadolinium","Gallium","Germanium","Gold","Hafnium","Hassium","Helium","Holmium","Hydrogen","Indium","Iodine","Iridium","Iron","Krypton","Lanthanum","Lawrencium","Lead","Lithium","Lutetium","Magnesium","Manganese","Meitnerium","Mendelevium","Mercury","Molybdenum","Neodymium","Neon","Neptunium","Nickel","Niobium","Nitrogen","Nobelium","Osmium","Oxygen","Palladium","Phosphorus","Platinum","Plutonium","Polonium","Potassium","Praseodymium","Promethium","Protactinium","Radium","Radon","Rhenium","Rhodium","Roentgenium","Rubidium","Ruthenium","Rutherfordium","Samarium","Scandium","Seaborgium","Selenium","Silicon","Silver","Sodium","Strontium","Sulfur","Tantalum","Technetium","Tellurium","Terbium","Thallium","Thorium","Thulium","Tin","Titanium","Tungsten","Ununbium","Ununhexium","Ununoctium","Ununpentium","Ununquadium","Ununseptium","Ununtrium","Ununium","Uranium","Vanadium","Xenon","Ytterbium","Yttrium","Zinc","Zirconium"]}';
let utterances = "AnswerIntent the answer is {Answer}\nAnswerIntent my answer is {Answer}\nAnswerIntent is it {Answer}\nAnswerIntent {Answer} is my answer\nAnswerOnlyIntent {Answer}\n\nAMAZON.StartOverIntent start game\nAMAZON.StartOverIntent new game\nAMAZON.StartOverIntent start\nAMAZON.StartOverIntent start new game\n\nDontKnowIntent i don't know\nDontKnowIntent don't know\nDontKnowIntent skip\nDontKnowIntent i don't know that\nDontKnowIntent who knows\nDontKnowIntent i don't know this question\nDontKnowIntent i don't know that one\nDontKnowIntent dunno";

let conf = new OpenWangZaiConfig('Custom', 'Chinese', 'sogourobot.skill.777777', 'nocturne', 'nocturne',
        intents, customTypes, utterances, 'HTTP');

console.log(conf);
